/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetScheduleRouteImport } from './routes/vet/schedule'
import { Route as VetProfileRouteImport } from './routes/vet/profile'
import { Route as VetDashboardRouteImport } from './routes/vet/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as publicSearchRouteImport } from './routes/(public)/search'
import { Route as customerProfileRouteImport } from './routes/(customer)/profile'
import { Route as customerCheckoutRouteImport } from './routes/(customer)/checkout'
import { Route as customerCartRouteImport } from './routes/(customer)/cart'
import { Route as VetPatientsRouteRouteImport } from './routes/vet/patients/route'
import { Route as VetAppointmentsRouteRouteImport } from './routes/vet/appointments/route'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as customerPetsRouteRouteImport } from './routes/(customer)/pets/route'
import { Route as customerAppointmentsRouteRouteImport } from './routes/(customer)/appointments/route'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as publicProductsIndexRouteImport } from './routes/(public)/products/index'
import { Route as customerOrdersIndexRouteImport } from './routes/(customer)/orders/index'
import { Route as VetPatientsPetIdRouteImport } from './routes/vet/patients/$petId'
import { Route as VetAppointmentsAppointmentIdRouteImport } from './routes/vet/appointments/$appointmentId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as publicProductsProductIdRouteImport } from './routes/(public)/products/$productId'
import { Route as publicCategoriesCategoryIdRouteImport } from './routes/(public)/categories/$categoryId'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'
import { Route as customerPetsPetIdRouteImport } from './routes/(customer)/pets/$petId'
import { Route as customerOrdersOrderIdRouteImport } from './routes/(customer)/orders/$orderId'
import { Route as customerAppointmentsAppointmentIdRouteImport } from './routes/(customer)/appointments/$appointmentId'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetScheduleRoute = VetScheduleRouteImport.update({
  id: '/vet/schedule',
  path: '/vet/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const VetProfileRoute = VetProfileRouteImport.update({
  id: '/vet/profile',
  path: '/vet/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VetDashboardRoute = VetDashboardRouteImport.update({
  id: '/vet/dashboard',
  path: '/vet/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSearchRoute = publicSearchRouteImport.update({
  id: '/(public)/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const customerProfileRoute = customerProfileRouteImport.update({
  id: '/(customer)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCheckoutRoute = customerCheckoutRouteImport.update({
  id: '/(customer)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCartRoute = customerCartRouteImport.update({
  id: '/(customer)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const VetPatientsRouteRoute = VetPatientsRouteRouteImport.update({
  id: '/vet/patients',
  path: '/vet/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const VetAppointmentsRouteRoute = VetAppointmentsRouteRouteImport.update({
  id: '/vet/appointments',
  path: '/vet/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const customerPetsRouteRoute = customerPetsRouteRouteImport.update({
  id: '/(customer)/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const customerAppointmentsRouteRoute =
  customerAppointmentsRouteRouteImport.update({
    id: '/(customer)/appointments',
    path: '/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProductsIndexRoute = publicProductsIndexRouteImport.update({
  id: '/(public)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const customerOrdersIndexRoute = customerOrdersIndexRouteImport.update({
  id: '/(customer)/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetPatientsPetIdRoute = VetPatientsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => VetPatientsRouteRoute,
} as any)
const VetAppointmentsAppointmentIdRoute =
  VetAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => VetAppointmentsRouteRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const publicProductsProductIdRoute = publicProductsProductIdRouteImport.update({
  id: '/(public)/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCategoriesCategoryIdRoute =
  publicCategoriesCategoryIdRouteImport.update({
    id: '/(public)/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/(public)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/(public)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const customerPetsPetIdRoute = customerPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => customerPetsRouteRoute,
} as any)
const customerOrdersOrderIdRoute = customerOrdersOrderIdRouteImport.update({
  id: '/(customer)/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const customerAppointmentsAppointmentIdRoute =
  customerAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => customerAppointmentsRouteRoute,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/admin/products/$productId/edit',
    path: '/admin/products/$productId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof customerAppointmentsRouteRouteWithChildren
  '/pets': typeof customerPetsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/vet/appointments': typeof VetAppointmentsRouteRouteWithChildren
  '/vet/patients': typeof VetPatientsRouteRouteWithChildren
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/profile': typeof customerProfileRoute
  '/search': typeof publicSearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/profile': typeof VetProfileRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/appointments/$appointmentId': typeof customerAppointmentsAppointmentIdRoute
  '/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/pets/$petId': typeof customerPetsPetIdRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRoute
  '/products/$productId': typeof publicProductsProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/vet/patients/$petId': typeof VetPatientsPetIdRoute
  '/orders': typeof customerOrdersIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof customerAppointmentsRouteRouteWithChildren
  '/pets': typeof customerPetsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/vet/appointments': typeof VetAppointmentsRouteRouteWithChildren
  '/vet/patients': typeof VetPatientsRouteRouteWithChildren
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/profile': typeof customerProfileRoute
  '/search': typeof publicSearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/profile': typeof VetProfileRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/appointments/$appointmentId': typeof customerAppointmentsAppointmentIdRoute
  '/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/pets/$petId': typeof customerPetsPetIdRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRoute
  '/products/$productId': typeof publicProductsProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/vet/patients/$petId': typeof VetPatientsPetIdRoute
  '/orders': typeof customerOrdersIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(customer)/appointments': typeof customerAppointmentsRouteRouteWithChildren
  '/(customer)/pets': typeof customerPetsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/vet/appointments': typeof VetAppointmentsRouteRouteWithChildren
  '/vet/patients': typeof VetPatientsRouteRouteWithChildren
  '/(customer)/cart': typeof customerCartRoute
  '/(customer)/checkout': typeof customerCheckoutRoute
  '/(customer)/profile': typeof customerProfileRoute
  '/(public)/search': typeof publicSearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/profile': typeof VetProfileRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/(customer)/appointments/$appointmentId': typeof customerAppointmentsAppointmentIdRoute
  '/(customer)/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/(customer)/pets/$petId': typeof customerPetsPetIdRoute
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(public)/categories/$categoryId': typeof publicCategoriesCategoryIdRoute
  '/(public)/products/$productId': typeof publicProductsProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/vet/patients/$petId': typeof VetPatientsPetIdRoute
  '/(customer)/orders/': typeof customerOrdersIndexRoute
  '/(public)/products/': typeof publicProductsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/pets'
    | '/admin/users'
    | '/vet/appointments'
    | '/vet/patients'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/search'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/profile'
    | '/vet/schedule'
    | '/appointments/$appointmentId'
    | '/orders/$orderId'
    | '/pets/$petId'
    | '/auth/login'
    | '/auth/register'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/admin/users/$userId'
    | '/vet/appointments/$appointmentId'
    | '/vet/patients/$petId'
    | '/orders'
    | '/products'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/pets'
    | '/admin/users'
    | '/vet/appointments'
    | '/vet/patients'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/search'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/profile'
    | '/vet/schedule'
    | '/appointments/$appointmentId'
    | '/orders/$orderId'
    | '/pets/$petId'
    | '/auth/login'
    | '/auth/register'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/admin/users/$userId'
    | '/vet/appointments/$appointmentId'
    | '/vet/patients/$petId'
    | '/orders'
    | '/products'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/(customer)/appointments'
    | '/(customer)/pets'
    | '/admin/users'
    | '/vet/appointments'
    | '/vet/patients'
    | '/(customer)/cart'
    | '/(customer)/checkout'
    | '/(customer)/profile'
    | '/(public)/search'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/profile'
    | '/vet/schedule'
    | '/(customer)/appointments/$appointmentId'
    | '/(customer)/orders/$orderId'
    | '/(customer)/pets/$petId'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/(public)/categories/$categoryId'
    | '/(public)/products/$productId'
    | '/admin/orders/$orderId'
    | '/admin/products/new'
    | '/admin/users/$userId'
    | '/vet/appointments/$appointmentId'
    | '/vet/patients/$petId'
    | '/(customer)/orders/'
    | '/(public)/products/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  customerAppointmentsRouteRoute: typeof customerAppointmentsRouteRouteWithChildren
  customerPetsRouteRoute: typeof customerPetsRouteRouteWithChildren
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  VetAppointmentsRouteRoute: typeof VetAppointmentsRouteRouteWithChildren
  VetPatientsRouteRoute: typeof VetPatientsRouteRouteWithChildren
  customerCartRoute: typeof customerCartRoute
  customerCheckoutRoute: typeof customerCheckoutRoute
  customerProfileRoute: typeof customerProfileRoute
  publicSearchRoute: typeof publicSearchRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  VetDashboardRoute: typeof VetDashboardRoute
  VetProfileRoute: typeof VetProfileRoute
  VetScheduleRoute: typeof VetScheduleRoute
  customerOrdersOrderIdRoute: typeof customerOrdersOrderIdRoute
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
  publicCategoriesCategoryIdRoute: typeof publicCategoriesCategoryIdRoute
  publicProductsProductIdRoute: typeof publicProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  customerOrdersIndexRoute: typeof customerOrdersIndexRoute
  publicProductsIndexRoute: typeof publicProductsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/schedule': {
      id: '/vet/schedule'
      path: '/vet/schedule'
      fullPath: '/vet/schedule'
      preLoaderRoute: typeof VetScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/profile': {
      id: '/vet/profile'
      path: '/vet/profile'
      fullPath: '/vet/profile'
      preLoaderRoute: typeof VetProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/dashboard': {
      id: '/vet/dashboard'
      path: '/vet/dashboard'
      fullPath: '/vet/dashboard'
      preLoaderRoute: typeof VetDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/search': {
      id: '/(public)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof publicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/profile': {
      id: '/(customer)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof customerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/checkout': {
      id: '/(customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof customerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/cart': {
      id: '/(customer)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof customerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/patients': {
      id: '/vet/patients'
      path: '/vet/patients'
      fullPath: '/vet/patients'
      preLoaderRoute: typeof VetPatientsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/appointments': {
      id: '/vet/appointments'
      path: '/vet/appointments'
      fullPath: '/vet/appointments'
      preLoaderRoute: typeof VetAppointmentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/pets': {
      id: '/(customer)/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof customerPetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/appointments': {
      id: '/(customer)/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof customerAppointmentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/products/': {
      id: '/(public)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof publicProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/orders/': {
      id: '/(customer)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof customerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/patients/$petId': {
      id: '/vet/patients/$petId'
      path: '/$petId'
      fullPath: '/vet/patients/$petId'
      preLoaderRoute: typeof VetPatientsPetIdRouteImport
      parentRoute: typeof VetPatientsRouteRoute
    }
    '/vet/appointments/$appointmentId': {
      id: '/vet/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/vet/appointments/$appointmentId'
      preLoaderRoute: typeof VetAppointmentsAppointmentIdRouteImport
      parentRoute: typeof VetAppointmentsRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/(public)/products/$productId': {
      id: '/(public)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof publicProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/categories/$categoryId': {
      id: '/(public)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/pets/$petId': {
      id: '/(customer)/pets/$petId'
      path: '/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof customerPetsPetIdRouteImport
      parentRoute: typeof customerPetsRouteRoute
    }
    '/(customer)/orders/$orderId': {
      id: '/(customer)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof customerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/appointments/$appointmentId': {
      id: '/(customer)/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof customerAppointmentsAppointmentIdRouteImport
      parentRoute: typeof customerAppointmentsRouteRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/admin/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface customerAppointmentsRouteRouteChildren {
  customerAppointmentsAppointmentIdRoute: typeof customerAppointmentsAppointmentIdRoute
}

const customerAppointmentsRouteRouteChildren: customerAppointmentsRouteRouteChildren =
  {
    customerAppointmentsAppointmentIdRoute:
      customerAppointmentsAppointmentIdRoute,
  }

const customerAppointmentsRouteRouteWithChildren =
  customerAppointmentsRouteRoute._addFileChildren(
    customerAppointmentsRouteRouteChildren,
  )

interface customerPetsRouteRouteChildren {
  customerPetsPetIdRoute: typeof customerPetsPetIdRoute
}

const customerPetsRouteRouteChildren: customerPetsRouteRouteChildren = {
  customerPetsPetIdRoute: customerPetsPetIdRoute,
}

const customerPetsRouteRouteWithChildren =
  customerPetsRouteRoute._addFileChildren(customerPetsRouteRouteChildren)

interface AdminUsersRouteRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface VetAppointmentsRouteRouteChildren {
  VetAppointmentsAppointmentIdRoute: typeof VetAppointmentsAppointmentIdRoute
}

const VetAppointmentsRouteRouteChildren: VetAppointmentsRouteRouteChildren = {
  VetAppointmentsAppointmentIdRoute: VetAppointmentsAppointmentIdRoute,
}

const VetAppointmentsRouteRouteWithChildren =
  VetAppointmentsRouteRoute._addFileChildren(VetAppointmentsRouteRouteChildren)

interface VetPatientsRouteRouteChildren {
  VetPatientsPetIdRoute: typeof VetPatientsPetIdRoute
}

const VetPatientsRouteRouteChildren: VetPatientsRouteRouteChildren = {
  VetPatientsPetIdRoute: VetPatientsPetIdRoute,
}

const VetPatientsRouteRouteWithChildren =
  VetPatientsRouteRoute._addFileChildren(VetPatientsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  customerAppointmentsRouteRoute: customerAppointmentsRouteRouteWithChildren,
  customerPetsRouteRoute: customerPetsRouteRouteWithChildren,
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  VetAppointmentsRouteRoute: VetAppointmentsRouteRouteWithChildren,
  VetPatientsRouteRoute: VetPatientsRouteRouteWithChildren,
  customerCartRoute: customerCartRoute,
  customerCheckoutRoute: customerCheckoutRoute,
  customerProfileRoute: customerProfileRoute,
  publicSearchRoute: publicSearchRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  VetDashboardRoute: VetDashboardRoute,
  VetProfileRoute: VetProfileRoute,
  VetScheduleRoute: VetScheduleRoute,
  customerOrdersOrderIdRoute: customerOrdersOrderIdRoute,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
  publicCategoriesCategoryIdRoute: publicCategoriesCategoryIdRoute,
  publicProductsProductIdRoute: publicProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  customerOrdersIndexRoute: customerOrdersIndexRoute,
  publicProductsIndexRoute: publicProductsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
