/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetScheduleRouteImport } from './routes/vet/schedule'
import { Route as VetDashboardRouteImport } from './routes/vet/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as customerCheckoutRouteImport } from './routes/(customer)/checkout'
import { Route as customerCartRouteImport } from './routes/(customer)/cart'
import { Route as VetAppointmentsIndexRouteImport } from './routes/vet/appointments/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminAdoptionIndexRouteImport } from './routes/admin/adoption/index'
import { Route as publicProductsIndexRouteImport } from './routes/(public)/products/index'
import { Route as publicAdoptionIndexRouteImport } from './routes/(public)/adoption/index'
import { Route as customerPetsIndexRouteImport } from './routes/(customer)/pets/index'
import { Route as customerOrdersIndexRouteImport } from './routes/(customer)/orders/index'
import { Route as customerAppointmentsIndexRouteImport } from './routes/(customer)/appointments/index'
import { Route as VetAppointmentsAppointmentIdRouteImport } from './routes/vet/appointments/$appointmentId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminAdoptionNewRouteImport } from './routes/admin/adoption/new'
import { Route as AdminAdoptionApplicationsRouteImport } from './routes/admin/adoption/applications'
import { Route as publicProductsProductIdRouteImport } from './routes/(public)/products/$productId'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'
import { Route as publicAdoptionPetIdRouteImport } from './routes/(public)/adoption/$petId'
import { Route as customerPetsNewRouteImport } from './routes/(customer)/pets/new'
import { Route as customerPetsPetIdRouteImport } from './routes/(customer)/pets/$petId'
import { Route as customerOrdersOrderIdRouteImport } from './routes/(customer)/orders/$orderId'
import { Route as customerAppointmentsNewRouteImport } from './routes/(customer)/appointments/new'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId.edit'
import { Route as AdminAdoptionPetIdEditRouteImport } from './routes/admin/adoption/$petId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetScheduleRoute = VetScheduleRouteImport.update({
  id: '/vet/schedule',
  path: '/vet/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const VetDashboardRoute = VetDashboardRouteImport.update({
  id: '/vet/dashboard',
  path: '/vet/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCheckoutRoute = customerCheckoutRouteImport.update({
  id: '/(customer)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const customerCartRoute = customerCartRouteImport.update({
  id: '/(customer)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const VetAppointmentsIndexRoute = VetAppointmentsIndexRouteImport.update({
  id: '/vet/appointments/',
  path: '/vet/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdoptionIndexRoute = AdminAdoptionIndexRouteImport.update({
  id: '/admin/adoption/',
  path: '/admin/adoption/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProductsIndexRoute = publicProductsIndexRouteImport.update({
  id: '/(public)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAdoptionIndexRoute = publicAdoptionIndexRouteImport.update({
  id: '/(public)/adoption/',
  path: '/adoption/',
  getParentRoute: () => rootRouteImport,
} as any)
const customerPetsIndexRoute = customerPetsIndexRouteImport.update({
  id: '/(customer)/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const customerOrdersIndexRoute = customerOrdersIndexRouteImport.update({
  id: '/(customer)/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const customerAppointmentsIndexRoute =
  customerAppointmentsIndexRouteImport.update({
    id: '/(customer)/appointments/',
    path: '/appointments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VetAppointmentsAppointmentIdRoute =
  VetAppointmentsAppointmentIdRouteImport.update({
    id: '/vet/appointments/$appointmentId',
    path: '/vet/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdoptionNewRoute = AdminAdoptionNewRouteImport.update({
  id: '/admin/adoption/new',
  path: '/admin/adoption/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdoptionApplicationsRoute =
  AdminAdoptionApplicationsRouteImport.update({
    id: '/admin/adoption/applications',
    path: '/admin/adoption/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicProductsProductIdRoute = publicProductsProductIdRouteImport.update({
  id: '/(public)/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/(public)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/(public)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAdoptionPetIdRoute = publicAdoptionPetIdRouteImport.update({
  id: '/(public)/adoption/$petId',
  path: '/adoption/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const customerPetsNewRoute = customerPetsNewRouteImport.update({
  id: '/(customer)/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const customerPetsPetIdRoute = customerPetsPetIdRouteImport.update({
  id: '/(customer)/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const customerOrdersOrderIdRoute = customerOrdersOrderIdRouteImport.update({
  id: '/(customer)/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const customerAppointmentsNewRoute = customerAppointmentsNewRouteImport.update({
  id: '/(customer)/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/admin/products/$productId/edit',
    path: '/admin/products/$productId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdoptionPetIdEditRoute = AdminAdoptionPetIdEditRouteImport.update({
  id: '/admin/adoption/$petId/edit',
  path: '/admin/adoption/$petId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/appointments/new': typeof customerAppointmentsNewRoute
  '/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/pets/$petId': typeof customerPetsPetIdRoute
  '/pets/new': typeof customerPetsNewRoute
  '/adoption/$petId': typeof publicAdoptionPetIdRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/products/$productId': typeof publicProductsProductIdRoute
  '/admin/adoption/applications': typeof AdminAdoptionApplicationsRoute
  '/admin/adoption/new': typeof AdminAdoptionNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/appointments': typeof customerAppointmentsIndexRoute
  '/orders': typeof customerOrdersIndexRoute
  '/pets': typeof customerPetsIndexRoute
  '/adoption': typeof publicAdoptionIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/admin/adoption': typeof AdminAdoptionIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/vet/appointments': typeof VetAppointmentsIndexRoute
  '/admin/adoption/$petId/edit': typeof AdminAdoptionPetIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/appointments/new': typeof customerAppointmentsNewRoute
  '/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/pets/$petId': typeof customerPetsPetIdRoute
  '/pets/new': typeof customerPetsNewRoute
  '/adoption/$petId': typeof publicAdoptionPetIdRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/products/$productId': typeof publicProductsProductIdRoute
  '/admin/adoption/applications': typeof AdminAdoptionApplicationsRoute
  '/admin/adoption/new': typeof AdminAdoptionNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/appointments': typeof customerAppointmentsIndexRoute
  '/orders': typeof customerOrdersIndexRoute
  '/pets': typeof customerPetsIndexRoute
  '/adoption': typeof publicAdoptionIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/admin/adoption': typeof AdminAdoptionIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/vet/appointments': typeof VetAppointmentsIndexRoute
  '/admin/adoption/$petId/edit': typeof AdminAdoptionPetIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(customer)/cart': typeof customerCartRoute
  '/(customer)/checkout': typeof customerCheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/schedule': typeof VetScheduleRoute
  '/(customer)/appointments/new': typeof customerAppointmentsNewRoute
  '/(customer)/orders/$orderId': typeof customerOrdersOrderIdRoute
  '/(customer)/pets/$petId': typeof customerPetsPetIdRoute
  '/(customer)/pets/new': typeof customerPetsNewRoute
  '/(public)/adoption/$petId': typeof publicAdoptionPetIdRoute
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(public)/products/$productId': typeof publicProductsProductIdRoute
  '/admin/adoption/applications': typeof AdminAdoptionApplicationsRoute
  '/admin/adoption/new': typeof AdminAdoptionNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/vet/appointments/$appointmentId': typeof VetAppointmentsAppointmentIdRoute
  '/(customer)/appointments/': typeof customerAppointmentsIndexRoute
  '/(customer)/orders/': typeof customerOrdersIndexRoute
  '/(customer)/pets/': typeof customerPetsIndexRoute
  '/(public)/adoption/': typeof publicAdoptionIndexRoute
  '/(public)/products/': typeof publicProductsIndexRoute
  '/admin/adoption/': typeof AdminAdoptionIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/vet/appointments/': typeof VetAppointmentsIndexRoute
  '/admin/adoption/$petId/edit': typeof AdminAdoptionPetIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/schedule'
    | '/appointments/new'
    | '/orders/$orderId'
    | '/pets/$petId'
    | '/pets/new'
    | '/adoption/$petId'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/admin/adoption/applications'
    | '/admin/adoption/new'
    | '/admin/products/new'
    | '/vet/appointments/$appointmentId'
    | '/appointments'
    | '/orders'
    | '/pets'
    | '/adoption'
    | '/products'
    | '/admin/adoption'
    | '/admin/orders'
    | '/admin/products'
    | '/vet/appointments'
    | '/admin/adoption/$petId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/schedule'
    | '/appointments/new'
    | '/orders/$orderId'
    | '/pets/$petId'
    | '/pets/new'
    | '/adoption/$petId'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/admin/adoption/applications'
    | '/admin/adoption/new'
    | '/admin/products/new'
    | '/vet/appointments/$appointmentId'
    | '/appointments'
    | '/orders'
    | '/pets'
    | '/adoption'
    | '/products'
    | '/admin/adoption'
    | '/admin/orders'
    | '/admin/products'
    | '/vet/appointments'
    | '/admin/adoption/$petId/edit'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/(customer)/cart'
    | '/(customer)/checkout'
    | '/admin/dashboard'
    | '/vet/dashboard'
    | '/vet/schedule'
    | '/(customer)/appointments/new'
    | '/(customer)/orders/$orderId'
    | '/(customer)/pets/$petId'
    | '/(customer)/pets/new'
    | '/(public)/adoption/$petId'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/(public)/products/$productId'
    | '/admin/adoption/applications'
    | '/admin/adoption/new'
    | '/admin/products/new'
    | '/vet/appointments/$appointmentId'
    | '/(customer)/appointments/'
    | '/(customer)/orders/'
    | '/(customer)/pets/'
    | '/(public)/adoption/'
    | '/(public)/products/'
    | '/admin/adoption/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/vet/appointments/'
    | '/admin/adoption/$petId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  customerCartRoute: typeof customerCartRoute
  customerCheckoutRoute: typeof customerCheckoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  VetDashboardRoute: typeof VetDashboardRoute
  VetScheduleRoute: typeof VetScheduleRoute
  customerAppointmentsNewRoute: typeof customerAppointmentsNewRoute
  customerOrdersOrderIdRoute: typeof customerOrdersOrderIdRoute
  customerPetsPetIdRoute: typeof customerPetsPetIdRoute
  customerPetsNewRoute: typeof customerPetsNewRoute
  publicAdoptionPetIdRoute: typeof publicAdoptionPetIdRoute
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
  publicProductsProductIdRoute: typeof publicProductsProductIdRoute
  AdminAdoptionApplicationsRoute: typeof AdminAdoptionApplicationsRoute
  AdminAdoptionNewRoute: typeof AdminAdoptionNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  VetAppointmentsAppointmentIdRoute: typeof VetAppointmentsAppointmentIdRoute
  customerAppointmentsIndexRoute: typeof customerAppointmentsIndexRoute
  customerOrdersIndexRoute: typeof customerOrdersIndexRoute
  customerPetsIndexRoute: typeof customerPetsIndexRoute
  publicAdoptionIndexRoute: typeof publicAdoptionIndexRoute
  publicProductsIndexRoute: typeof publicProductsIndexRoute
  AdminAdoptionIndexRoute: typeof AdminAdoptionIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  VetAppointmentsIndexRoute: typeof VetAppointmentsIndexRoute
  AdminAdoptionPetIdEditRoute: typeof AdminAdoptionPetIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/schedule': {
      id: '/vet/schedule'
      path: '/vet/schedule'
      fullPath: '/vet/schedule'
      preLoaderRoute: typeof VetScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/dashboard': {
      id: '/vet/dashboard'
      path: '/vet/dashboard'
      fullPath: '/vet/dashboard'
      preLoaderRoute: typeof VetDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/checkout': {
      id: '/(customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof customerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/cart': {
      id: '/(customer)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof customerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/appointments/': {
      id: '/vet/appointments/'
      path: '/vet/appointments'
      fullPath: '/vet/appointments'
      preLoaderRoute: typeof VetAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adoption/': {
      id: '/admin/adoption/'
      path: '/admin/adoption'
      fullPath: '/admin/adoption'
      preLoaderRoute: typeof AdminAdoptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/products/': {
      id: '/(public)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof publicProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/adoption/': {
      id: '/(public)/adoption/'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof publicAdoptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/pets/': {
      id: '/(customer)/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof customerPetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/orders/': {
      id: '/(customer)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof customerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/appointments/': {
      id: '/(customer)/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof customerAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/appointments/$appointmentId': {
      id: '/vet/appointments/$appointmentId'
      path: '/vet/appointments/$appointmentId'
      fullPath: '/vet/appointments/$appointmentId'
      preLoaderRoute: typeof VetAppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adoption/new': {
      id: '/admin/adoption/new'
      path: '/admin/adoption/new'
      fullPath: '/admin/adoption/new'
      preLoaderRoute: typeof AdminAdoptionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adoption/applications': {
      id: '/admin/adoption/applications'
      path: '/admin/adoption/applications'
      fullPath: '/admin/adoption/applications'
      preLoaderRoute: typeof AdminAdoptionApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/products/$productId': {
      id: '/(public)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof publicProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/adoption/$petId': {
      id: '/(public)/adoption/$petId'
      path: '/adoption/$petId'
      fullPath: '/adoption/$petId'
      preLoaderRoute: typeof publicAdoptionPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/pets/new': {
      id: '/(customer)/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof customerPetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/pets/$petId': {
      id: '/(customer)/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof customerPetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/orders/$orderId': {
      id: '/(customer)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof customerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/appointments/new': {
      id: '/(customer)/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof customerAppointmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/admin/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adoption/$petId/edit': {
      id: '/admin/adoption/$petId/edit'
      path: '/admin/adoption/$petId/edit'
      fullPath: '/admin/adoption/$petId/edit'
      preLoaderRoute: typeof AdminAdoptionPetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  customerCartRoute: customerCartRoute,
  customerCheckoutRoute: customerCheckoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  VetDashboardRoute: VetDashboardRoute,
  VetScheduleRoute: VetScheduleRoute,
  customerAppointmentsNewRoute: customerAppointmentsNewRoute,
  customerOrdersOrderIdRoute: customerOrdersOrderIdRoute,
  customerPetsPetIdRoute: customerPetsPetIdRoute,
  customerPetsNewRoute: customerPetsNewRoute,
  publicAdoptionPetIdRoute: publicAdoptionPetIdRoute,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
  publicProductsProductIdRoute: publicProductsProductIdRoute,
  AdminAdoptionApplicationsRoute: AdminAdoptionApplicationsRoute,
  AdminAdoptionNewRoute: AdminAdoptionNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  VetAppointmentsAppointmentIdRoute: VetAppointmentsAppointmentIdRoute,
  customerAppointmentsIndexRoute: customerAppointmentsIndexRoute,
  customerOrdersIndexRoute: customerOrdersIndexRoute,
  customerPetsIndexRoute: customerPetsIndexRoute,
  publicAdoptionIndexRoute: publicAdoptionIndexRoute,
  publicProductsIndexRoute: publicProductsIndexRoute,
  AdminAdoptionIndexRoute: AdminAdoptionIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  VetAppointmentsIndexRoute: VetAppointmentsIndexRoute,
  AdminAdoptionPetIdEditRoute: AdminAdoptionPetIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
